// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TagId { get; set; }

    public virtual Tag Tag { get; set; }

    public virtual ICollection<UserGroup> UserGroups { get; set; } = new List<UserGroup>();
}